# https://chshersh.github.io/posts/2019-02-25-haskell-travis

language: haskell
ghc: "8.6"
cabal: "2.4"

git:
  depth: 5

install:
  - cabal new-update
  - cabal new-build --enable-tests --enable-benchmarks

script:
  - cabal new-test --enable-tests

cache:
  directories:
  - "$HOME/.cabal/store"
