# https://chshersh.github.io/posts/2019-02-25-haskell-travis

language: haskell
ghc:
  - "8.6"
cabal: "2.4"

cache:
  directories:
  - "$HOME/.cabal/store"

install:
  - ghc --version
  - cabal --version
  - cabal new-update
  - cabal new-build --enable-tests --enable-benchmarks

script:
  - cabal new-test --enable-tests
